// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const String _databaseURL = 'https://ips-medident-default-rtdb.firebaseio.com';

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCRpxCV1Clh27U_51oNLAH8hmTbvJ8lk38",
    authDomain: "ips-medident.firebaseapp.com",
    databaseURL: _databaseURL,
    projectId: "ips-medident",
    storageBucket: "ips-medident.firebasestorage.app",
    messagingSenderId: "435865924056",
    appId: "1:435865924056:web:07b721ee76d40b056282ad",
    measurementId: "G-063DY2YTCQ"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2n8hcCIr6J1tE1pIYSgp6IftR9xnCwec',
    appId: '1:435865924056:android:f75f0e860880f4296282ad',
    messagingSenderId: '435865924056',
    projectId: 'ips-medident',
    databaseURL: _databaseURL,
    storageBucket: 'ips-medident.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGtl_1dzSe3j9GadXu4fUhkr2CRlp_Qzc',
    appId: '1:435865924056:ios:ac3dfd486d843c5e6282ad',
    messagingSenderId: '435865924056',
    projectId: 'ips-medident',
    databaseURL: _databaseURL,
    storageBucket: 'ips-medident.firebasestorage.app',
    iosBundleId: 'com.medident.medident',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGtl_1dzSe3j9GadXu4fUhkr2CRlp_Qzc',
    appId: '1:435865924056:ios:ac3dfd486d843c5e6282ad',
    messagingSenderId: '435865924056',
    projectId: 'ips-medident',
    databaseURL: _databaseURL,
    storageBucket: 'ips-medident.firebasestorage.app',
    iosBundleId: 'com.medident.medident',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRpxCV1Clh27U_51oNLAH8hmTbvJ8lk38',
    appId: '1:435865924056:web:373480380257c5816282ad',
    messagingSenderId: '435865924056',
    projectId: 'ips-medident',
    authDomain: 'ips-medident.firebaseapp.com',
    databaseURL: _databaseURL,
    storageBucket: 'ips-medident.firebasestorage.app',
    measurementId: 'G-Q9B5W62NZ2',
  );

}
